{
 "title": "Container Platform Main Dashboard",
 "description": "For monitong Cluster Status and Critical Parameter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"} == 1)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Kubelets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_node_name{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{job=\"kubelet\", metrics_path=\"/metrics\"}) OR sum(kubelet_running_pod_count{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{job=\"kubelet\", metrics_path=\"/metrics\"}) OR sum(kubelet_running_container_count{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Number Per Node",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (node) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube Node Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "max by(node, condition) (kube_node_status_condition{status=\"true\", condition=~\"Ready|MemoryPressure|DiskPressure|PIDPressure\"})"
    }
   ]
  },
  {
   "title": "Node Resource Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "100 * avg by (instance) (\n  rate(node_cpu_seconds_total{mode!=\"idle\", mode!=\"iowait\", mode!=\"steal\", job=\"node-exporter\", instance=~\"container-okd.*\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (\n  1 - avg by (instance) (node_memory_MemAvailable_bytes)\n      /\n      avg by (instance) (node_memory_MemTotal_bytes)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (\n  1 - (\n    node_filesystem_avail_bytes{mountpoint=\"/var\", fstype!=\"\"}\n    /\n    node_filesystem_size_bytes{mountpoint=\"/var\", fstype!=\"\"}\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", instance=~\"container-okd-.*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", instance=~\"container-okd-.*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance) (\n  rate(node_network_receive_bytes_total{job=\"node-exporter\", device!=\"lo\", instance=~\"container-okd-.*\"}[$__rate_interval]) * 8\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance) (\nrate(node_network_transmit_bytes_total{job=\"node-exporter\", device!=\"lo\", instance=~\"container-okd-.*\"}[$__rate_interval]) * 8\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}