basic_auth_users:
  olsmonitor: Password ที่ Gen จาก HTPASSWD ด้วยคำสั่ง htpasswd -nBC 12 "" | tr -d ':\n'  แล้วมันจะให้กรอก password ที่ต้องการ แล้ว encode ให้
tls_server_config:
  cert_file: /etc/node_exporter/tls.crt
  key_file: /etc/node_exporter/tls.key
  #client_auth_type: RequireAndVerifyClientCert
  #client_ca_file: /etc/node_exporter/ca.crt
