###########  you can use command to create for auto excoded base64 ############
##  kubectl create secret generic node-exporter-tls-secret --from-file=ca.crt=ca.crt --from-file=tls.crt=tls.crt --from-file=tls.key=tls.key -n monitoring
###########  encode command for write yaml ###############
##  base64 -w 0 ca.crt
##
apiVersion: v1
kind: Secret
metadata:
  name: node-exporter-tls-secret
  namespace: monitoring
type: Opaque
data:
  ca.crt:  <base64-encoded-ca-cert>
  tls.crt: <base64-encoded-tls-cert>
  tls.key: <base64-encoded-tls-key>
